### ISSUE TITLE
Circular import error

### ISSUE THREAD

**Issue by samiit** [widgetti/solara#26]
Hi everyone,

After installing the latest Solara (as of today, 1.0.3) and trying to run the simple example shared by @maartenbreddels [here](https://github.com/voila-dashboards/voila-vuetify/issues/12#issuecomment-1378779064)

I am getting a circular import error. But things are fine if I use version 0.19.1

I tried to use even 1.0.0 version, but always get this error. Can someone please help?

Thanks,
Sam

**Comment by samiit** [comment]
More specifically, the error I get is:

```
...

ImportError: cannot import name 'get_current_context' from partially initialized module 'solara.server.app' (most likely due to a circular import) (/home/sam/Projects/Learning/Python/WebApps/FastAPI/FastAPI_Solara/venv/lib/python3.9/site-packages/solara/server/app.py)

```

**Comment by maartenbreddels** [comment]
Hi Sam,

Yes, I noticed that as well when I was trying this out on github codespaces. I noticed it was due to a new ipykernel actually, that triggered a different code path.
This was solved in ed35df9bb327d1230ce622aaaf67730e64750375 which will be released soon (I think today) in 1.0.4.

**Comment by maartenbreddels** [comment]
If you want to try it out, see the https://solara.dev/docs/installing instructions how to install a dev version, or install from master.

**Comment by samiit** [comment]
I tried that installing from master using

```
pip install git+https://github.com/widgetti/solara.git@master
```

but still get that error.

**Comment by samiit** [comment]
But I managed now to use the [https://solara.dev/docs/installing](https://solara.dev/docs/installing) instruction and it is working now!

Thanks.

**Comment by maartenbreddels** [comment]
Do you mean that:
```
$ pip install git+https://github.com/widgetti/solara.git@master
```

Did not work? 

But
```
$ pip install "solara @ git+https://github.com/widgetti/solara"
```
worked ?

**Comment by samiit** [comment]
Yes. But I will confirm again. Maybe I did something wrong.

**Comment by samiit** [comment]
Hi @maartenbreddels 

I checked now and both give the same results. Thanks.
